# 配置文件路径相关(程序运行时会自动处理动态路径，此处为相对/默认值)
[path]
current_dir = "."
download_dir = "./downloads"
cover_dir = "./downloads/covers"
playlist_file = "playlists.txt"
album_file = "albums.txt"
track_file = "tracks.txt"

# HTTP请求头配置
[headers]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
referer = "https://music.163.com/"

# 重试配置
[retry]
max_retries = 5
delay = 0.1

# 下载相关配置
[download]
request_delay = 0.1 # 相邻两次请求间隔

# 歌曲详情
[track]
translated_name = true # 是否在歌曲标题中添加译名

# 歌词配置
[lyric]
enable = true # 是否下载歌词
translation = true # 是否下载翻译歌词
romaji = false #是否下载罗马音歌词(默认关闭)

# 搜索配置
[search]
limit = 10 # 最大搜索数量
